#version 450
layout(local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rgba8) uniform readonly image2D aSampler;
layout(binding = 1, rgba8) uniform readonly image2D bSampler;
layout(binding = 2, rgba8) uniform image2D outputImage;

void main()
{
	vec4 a;
	vec4 b;
	vec4 c;
	vec4 f;
	vec4 t1;
	float f1;
	ivec2 uv;
	uv = ivec2(gl_GlobalInvocationID.xy);
	a = imageLoad(aSampler, uv);
	b = imageLoad(bSampler, uv);
	// 22.划分 
	c = a / b;
	imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), c);
}
